[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/static/js/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/static/css/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200